"""initial_schema_with_production_fields

Revision ID: 15d19543f13c
Revises: 
Create Date: 2026-06-11 15:36:27.808376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d19543f13c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_id'), ['id'], unique=False)

    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('camera_name', sa.String(length=255), nullable=False),
    sa.Column('rtsp_url', sa.String(length=2048), nullable=False),
    sa.Column('is_storage_camera', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('coverage_weight', sa.Float(), nullable=False),
    sa.Column('roi_polygon', sa.JSON(), nullable=True),
    sa.Column('camera_status', sa.String(length=20), nullable=False),
    sa.Column('last_successful_capture', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_id'), ['id'], unique=False)

    op.create_table('occupancy_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_percentage', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupancy_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupancy_reading_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancy_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupancy_reading_id'))

    op.drop_table('occupancy_reading')
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_id'))

    op.drop_table('camera')
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_id'))

    op.drop_table('warehouse')
    # ### end Alembic commands ###
